sonar.projectKey=TheCodeCrewUTEC_DevOpsInterfascia
sonar.projectName=DevOpsInterfascia
sonar.sources=.
sonar.organization=thecodecrewutec
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.venv/**,**/.git/**